### PR TITLE
Development

### PR DESCRIPTION
**Pull request by danilozag1992**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
- Responsive

- [ ] You page must be responsive in all screen sizes and use the same approach of the original page in all screen sizes as well(This must be applied to all sections):

image

image

image

image

- [ ] All styles should match with the respective breakpoint.

- Navigation bar

- [ ] Your navbar should use fixed positioning

- [ ] It should display the TNW logo at the leftmost part of it

- [ ] It should have a search icon and a hamburger (bars) icon at the rightmost part of it(only in the smal screen sizes)

- Apps section

- [ ] All apps section and similar should have eight articles, each one wrapped around a pair of `article` HTML tags

- [ ]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

- [ ]  There are one  error in your CSS code. Check it using this CSS [validator](https://jigsaw.w3.org/css-validator/) . Ignore the warnings.

**Comment by Torres-ssf** [comment]
Hi there team
You are doing a great work on this project. But still have some changes that we need to do. Microverse guidelines require that this project looks a lot similar to the original page. meaning that your project must match the style of each breakpoint of the original one. You have to do that for all sections.
Example:
- [ ] 767px and smaller
image


- [ ] 768px - 1023px
image

- [ ] 1024px and higher 
image

- [ ] Again this you have to match the style not only for the 'latest new' section but for all the other ones.

- [ ] Give a `background-color: white;` to your navbar in smaller breakpoints.

Kindly make these changes and submit for code review again.

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
Hi there team
You are working hard on this project and should be proud of it. But it's not ready yet. I'm sorry team but Microverse guidelines for this project require it to be fully responsive. The best approach to achieve that is defining the size of the containers with percentage (Ex. `width: 100%`). 
The latest news for example: 

image

In 1024px and higher breakpoint we need to have 4 articles per line. An easy solution is giving each article a width of 25% and for the father container a width of 100%.

image

In 768px - 1024px breakpoint we need to have 3 articles per line. An easy solution is giving each article a width of 33.33% and for the father container a width of 100%.

Try to use this approach in all breakpoint to make your page more responsive. Try to use fixed sizes only for images and other situations. Remember that padding can affect the size of the containers if you do not set `box-sizing: border-box`

Your page must include the lastest deals section

Please if you are struggling in any of those changes call me slack and I will help you out.

**Comment by mosaaleb** [comment]
# Under Review

**Comment by Oghenebrume50** [comment]
reviewing .......

**Comment by Oghenebrume50** [comment]
Hi team, this is cool, good job. You guys can submit the project completion form and move ahead. :)

**Pull request merged**
